#!/bin/bash
# Fetch the current Caffeine version from the compiler repo and update src/version.gleam

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
CAFFEINE_LANG_REPO="${CAFFEINE_LANG_REPO:-$PROJECT_DIR/../caffeine_lang}"
VERSION_FILE="$CAFFEINE_LANG_REPO/src/caffeine_lang/constants.gleam"
OUTPUT_FILE="$PROJECT_DIR/src/version.gleam"

if [ -f "$VERSION_FILE" ]; then
  VERSION=$(grep -o '"[0-9]\+\.[0-9]\+\.[0-9]\+"' "$VERSION_FILE" | tr -d '"')
else
  VERSION="unknown"
fi

# Update the version.gleam file
cat > "$OUTPUT_FILE" << EOF
// Auto-generated by scripts/fetch_version.sh - do not edit manually
pub const latest_version = "v$VERSION"
EOF

echo "$VERSION"
