#!/bin/bash
# Fetches the latest Caffeine release version from GitHub and generates src/version.gleam

set -e

REPO="Brickell-Research/caffeine_lang"
OUTPUT_FILE="src/version.gleam"

# Fetch latest release tag from GitHub API
VERSION=$(curl -s "https://api.github.com/repos/${REPO}/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')

if [ -z "$VERSION" ]; then
    echo "Warning: Could not fetch version from GitHub, using fallback"
    VERSION="v0.2.8"
fi

echo "Fetched version: $VERSION"

# Generate the Gleam file
cat > "$OUTPUT_FILE" << EOF
// Auto-generated by scripts/fetch_version.sh - do not edit manually
pub const latest_version = "$VERSION"
EOF

echo "Generated $OUTPUT_FILE"
